runtime: java
env: flex

env_variables:
  SPRING_DATASOURCE_URL: "mongodb+srv://allindiatelagabalijakapusangam:Admin123@communityproject.okfwe.mongodb.net/CommunityProject?retryWrites=true&w=majority&appName=CommunityProject"
